language: node_js
node_js:
 - "node"
sudo: required
dist: trusty
addons:
    chrome: stable
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
before_install:
  npm install karma-cli -g
notifications:
  email:
    on_success: never
    on_failure: never