language: node_js
node_js:
  - "6"

addons:
  chrome: "stable"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

# script:
#   - node test/none_zero.js
#   - mocha test/test.js

script: mocha test/test.js

before_install:
  npm install karma-cli -g 
